<div <?php echo \Flywheel\Html\Html::serializeHtmlOption($pagination->htmlOptions); ?>>
    <?php if($pagination->totalPage > 1) :?>
        <?php if ($pagination->showTotalPage) :?>
            <span><?php echo $pagination->total?> <?php echo $pagination->items ?> / <?php echo $pagination->totalPage ?> <?php td('pages'); ?></span>
        <?php endif; ?>
        <ul class="paging">
            <?php if ($pagination->currentPage != 1) :?>
                <li><a href="<?php echo $pagination->createLink(1); ?>">&laquo; <?php td('First'); ?></a></li>
            <?php endif; ?>
            <?php if ($pagination->currentPage > 1) : ?>
                <li><a href="<?php echo $pagination->createLink($pagination->currentPage - 1); ?>">&lt;</a></li>
            <?php endif; ?>
            <?php if ($pagination->startPage > 2) :?>
                <li><span>...</span></li>
            <?php endif ;?>
            <?php for ($i = $pagination->startPage; $i <= ($pagination->startPage + $pagination->numPageShow - 1) && ($i <= $pagination->totalPage); ++$i) : ?>
                <?php if ($i == $pagination->currentPage) : ?>
                    <li><span><?php echo $i; ?></span></li>
                <?php else : ?>
                    <li><a href="<?php echo $pagination->createLink($i); ?>"><?php echo $i; ?></a></li>
                <?php endif; ?>
            <?php endfor; ?>
            <?php if ($i< $pagination->totalPage) : ?>
                <li><span>...</span></li>
            <?php endif; ?>
            <?php if ($pagination->currentPage < $pagination->totalPage) : ?>
                <li><a href="<?php echo $pagination->createLink($pagination->currentPage + 1); ?>">&gt;</a></li>
            <?php endif; ?>
            <?php if ($pagination->currentPage != $pagination->totalPage) : ?>
                <li><a href="<?php echo $pagination->createLink($pagination->totalPage); ?>"><?php td('Last');?> &raquo;</a></li>
            <?php endif; ?>
        </ul>
    <?php endif; ?>
</div>